on:
  push:
    branches:
      - src

jobs:
  nikola_build:
    # Only do the whole deploy if this is src branch on the main repo.
    # This just prevents the action from running when people are working
    # on private forks.
    if: github.repository == 'planetarypy/planetarypy.github.io'
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
