on:
  pull_request:
    branches:
      - src

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Nikola Build Only'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build Nikola
      uses: getnikola/nikola-action@v8
      with:
        dry_run: true
